import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const port = process.env.CDP_PORT ?? '9230';
const origin = 'http://127.0.0.1:5173';
const tabs = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
const tab = tabs.find(item => item.type === 'page' && item.url.startsWith(origin));
assert.ok(tab, 'isolated test tab missing');
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
let sequence = 1;
const jobs = new Map();
ws.addEventListener('message', event => { const message = JSON.parse(event.data), job = jobs.get(message.id); if (!job) return; jobs.delete(message.id); message.error ? job.reject(Error(message.error.message)) : job.resolve(message.result); });
const call = (method, params = {}) => new Promise((resolve, reject) => { const id = sequence++; jobs.set(id, { resolve, reject }); ws.send(JSON.stringify({ id, method, params })); });
async function evaluate(expression) { const result = await call('Runtime.evaluate', { awaitPromise: true, returnByValue: true, expression }); if (result.exceptionDetails) throw Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.text); return result.result.value; }
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(expression, expected = true) { for (let i = 0; i < 60; i++) { const value = await evaluate(expression); if (expected === true ? value : value === expected) return value; await pause(150); } throw Error(`Timed out: ${expression}`); }
await call('Emulation.setDeviceMetricsOverride', { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false });
async function shot(path) { const result = await call('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); await writeFile(path, Buffer.from(result.data, 'base64')); }
await call('Storage.clearDataForOrigin', { origin, storageTypes: 'indexeddb' });
await call('Page.navigate', { url: origin + '/' }); await pause(500);
await evaluate('(' + (async function () {
  const { createEmptyProject } = await import('/src/domain/project.ts');
  const { commitProject } = await import('/src/persistence/indexedDb.ts');
  const state = createEmptyProject('enhancement-browser-qa');
  for (let month = 1; month <= 12; month++) {
    const canvas = document.createElement('canvas'); canvas.width = 360; canvas.height = 320;
    const ctx = canvas.getContext('2d');
    const hue = (month - 1) * 30;
    ctx.fillStyle = `hsl(${hue} 64% 48%)`; ctx.fillRect(0, 0, 360, 320);
    ctx.fillStyle = `hsl(${(hue + 120) % 360} 44% 35%)`; ctx.fillRect(0, 0, 90, 320);
    const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
    const assetId = 'a' + month, itemId = 'i' + month;
    state.assets[assetId] = { id: assetId, blob, mime: 'image/png', fileName: `${month}.png`, byteSize: blob.size, decodedWidth: 360, decodedHeight: 320, importedAt: '' };
    state.project.photoItems[itemId] = { id: itemId, assetId, createdAt: '' };
    state.project.months[month].photoItemId = itemId;
    state.project.months[month].crop = { zoom: 1, offsetX: 0, offsetY: 0 };
  }
  await commitProject(state, null);
}).toString() + ')()');
await call('Page.navigate', { url: origin + '/' }); await pause(600);
assert.equal(await evaluate("document.title"), 'Calendar Design Studio · 2027');
assert.ok(await evaluate("document.querySelector('.brand__wordmark')?.textContent.includes('Design Studio')"));
assert.equal((await fetch(origin + '/favicon.svg')).status, 200);
await evaluate("[...document.querySelectorAll('.entry-page button')].find(b => b.textContent.includes('继续编辑日历')).click()");
await pause(180);
await evaluate("[...document.querySelectorAll('.desktop-nav button')].find(b => b.textContent.includes('预览与导出')).click()");
await pause(180);
assert.ok(await evaluate("document.querySelector('.review-completion')?.textContent.includes('12 / 12')"));
await evaluate("[...document.querySelectorAll('.set-color-panel button')].find(b => b.textContent.includes('推荐配色')).click()");
await until("document.querySelectorAll('.set-color-row').length === 12");
const proposal = await evaluate("[...document.querySelectorAll('.set-color-row')].map(row => row.lastElementChild.textContent)");
assert.ok(new Set(proposal).size >= 6, `month palette insufficiently varied: ${proposal}`);
await shot('qa/enhancement-color-preview-desktop.png');
await evaluate("[...document.querySelectorAll('.set-color-sheet button')].find(b => b.textContent.includes('应用推荐配色 · 12')).click()");
await pause(900);
const applied = await evaluate('(' + (async function () { const { loadProject } = await import('/src/persistence/indexedDb.ts'); const state = await loadProject(); return { colors: Object.values(state.project.months).map(slot => slot.style.background), undo: state.project.colorBatchUndo }; }).toString() + ')()');
assert.ok(new Set(applied.colors).size >= 6);
assert.equal(Object.keys(applied.undo).length, 12);
await call('Page.navigate', { url: origin + '/' }); await pause(500);
await evaluate("[...document.querySelectorAll('.entry-page button')].find(b => b.textContent.includes('继续编辑日历')).click()"); await pause(120);
await evaluate("[...document.querySelectorAll('.desktop-nav button')].find(b => b.textContent.includes('预览与导出')).click()"); await pause(120);
assert.ok(await evaluate("[...document.querySelectorAll('.set-color-panel button')].some(b => b.textContent.includes('撤销本次配色'))"));
await evaluate("[...document.querySelectorAll('.set-color-panel button')].find(b => b.textContent.includes('撤销本次配色')).click()"); await pause(900);
const restored = await evaluate('(' + (async function () { const { loadProject } = await import('/src/persistence/indexedDb.ts'); const state = await loadProject(); return { colors: Object.values(state.project.months).map(slot => slot.style.background), undo: state.project.colorBatchUndo ?? null }; }).toString() + ')()');
assert.ok(restored.colors.every(color => color === '#FFFFFF')); assert.equal(restored.undo, null);
await evaluate("document.querySelector('.review-card').click()"); await pause(140);
assert.ok(await evaluate("getComputedStyle(document.querySelector('.proof-workspace')).backgroundImage.includes('linear-gradient')"));
await evaluate("[...document.querySelectorAll('.sample-color-trigger')][0].click()");
await until("document.querySelectorAll('.photo-recommendations__item').length === 3");
const choices = await evaluate("[...document.querySelectorAll('.photo-recommendations__item')].map(b => b.querySelector('small').textContent)");
assert.equal(new Set(choices).size, 3);
await evaluate("document.querySelectorAll('.photo-recommendations__item')[2].click()"); await pause(120);
const proofColor = await evaluate("getComputedStyle(document.querySelector('.proof-workspace .calendar-proof')).getPropertyValue('--proof-background').trim()");
assert.equal(proofColor, choices[2]);
await evaluate("[...document.querySelectorAll('.important-controls__grid button')].find(b => b.textContent === '14').click()");
assert.ok(await evaluate("[...document.querySelectorAll('.proof-workspace .calendar-proof__grid .is-important')].some(e => e.textContent === '14')"));
await evaluate("[...document.querySelectorAll('.important-controls__grid button')].find(b => b.textContent === '14').click()");
assert.equal(await evaluate("[...document.querySelectorAll('.proof-workspace .calendar-proof__grid .is-important')].some(e => e.textContent === '14')"), false);
await evaluate("[...document.querySelectorAll('.important-controls__grid button')].find(b => b.textContent === '14').click()");
await pause(900);
await call('Page.navigate', { url: origin + '/' }); await pause(500);
await evaluate("[...document.querySelectorAll('.entry-page button')].find(b => b.textContent.includes('继续编辑日历')).click()"); await pause(200);
assert.ok(await evaluate("[...document.querySelectorAll('.proof-workspace .calendar-proof__grid .is-important')].some(e => e.textContent === '14')"));
const image = await evaluate('(' + (async function () {
  const { loadProject } = await import('/src/persistence/indexedDb.ts');
  const { renderMonthImage } = await import('/src/export/canvasRenderer.ts');
  const { renderFullSet } = await import('/src/export/exportController.ts');
  const { buildMonthRenderModel } = await import('/src/domain/renderModel.ts');
  const state = await loadProject();
  const model = buildMonthRenderModel(1, state);
  const withMark = await renderMonthImage(state, 1, 'digital', 'png');
  const fullSet = await renderFullSet(state, () => {});
  if (fullSet.length !== 12 || fullSet[0].fileName !== '01-January-2027.png') throw Error('full-set missing marked month');
  const withoutState = structuredClone(state); withoutState.project.months[1].importantDays = [];
  const withoutMark = await renderMonthImage(withoutState, 1, 'digital', 'png');
  const read = async blob => { const bitmap = await createImageBitmap(blob); const canvas = document.createElement('canvas'); canvas.width = bitmap.width; canvas.height = bitmap.height; const context = canvas.getContext('2d'); context.drawImage(bitmap, 0, 0); bitmap.close(); return context.getImageData(0, 0, canvas.width, canvas.height).data; };
  const a = await read(withMark.blob), b = await read(withoutMark.blob), batchPixels = await read(fullSet[0].blob);
  const index = model.calendar.cells.indexOf(14), col = index % 7, row = Math.floor(index / 7);
  const centerX = model.geometry.dates.left + (col + 0.5) * model.geometry.dates.width / 7;
  const centerY = model.geometry.dates.top + (row + 0.5) * model.geometry.dates.height / 6;
  let different = 0, batchMatches = true;
  for (let y = Math.floor(centerY - 30); y < centerY + 30; y++) for (let x = Math.floor(centerX - 35); x < centerX + 35; x++) { const offset = (y * 1200 + x) * 4; if (a[offset] !== b[offset] || a[offset + 1] !== b[offset + 1] || a[offset + 2] !== b[offset + 2]) different++; if (a[offset] !== batchPixels[offset] || a[offset + 1] !== batchPixels[offset + 1] || a[offset + 2] !== batchPixels[offset + 2]) batchMatches = false; }
  return { different, batchMatches, fullSetCount: fullSet.length, importantInk: model.importantInk, importantDays: model.importantDays, width: 1200, height: 1800 };
}).toString() + ')()');
assert.equal(image.batchMatches, true);
assert.ok(image.different > 50, `PNG date ink unchanged: ${JSON.stringify(image)}`);
await shot('qa/enhancement-editor-desktop.png');
await call('Emulation.setDeviceMetricsOverride', { width: 320, height: 720, deviceScaleFactor: 1, mobile: true });
await pause(180);
const phone = await evaluate("({ overflow: document.documentElement.scrollWidth > innerWidth, brand: !!document.querySelector('.brand__wordmark'), dateButton: !!document.querySelector('.mobile-style-trigger') })");
assert.equal(phone.overflow, false, JSON.stringify(phone));
await shot('qa/enhancement-editor-phone.png');
await call('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
assert.equal(await evaluate("getComputedStyle(document.querySelector('.proof-workspace .calendar-proof')).animationName"), 'none');
await call('Emulation.setEmulatedMedia', { features: [] });
await call('Emulation.clearDeviceMetricsOverride');
ws.close();
console.log(JSON.stringify({ pass: true, choices, proposalUnique: new Set(proposal).size, image, phone }));
