import assert from 'node:assert/strict';
const target=(await (await fetch('http://127.0.0.1:9228/json/list')).json()).find(x=>x.type==='page'&&x.url.startsWith('http://'));assert.ok(target);const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=1;const jobs=new Map();ws.addEventListener('message',e=>{const d=JSON.parse(e.data),j=jobs.get(d.id);if(!j)return;jobs.delete(d.id);d.error?j.reject(Error(d.error.message)):j.resolve(d.result);});const call=(method,params={})=>new Promise((resolve,reject)=>{const k=id++;jobs.set(k,{resolve,reject});ws.send(JSON.stringify({id:k,method,params}));});const evalCode=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description??r.exceptionDetails.text);return r.result.value;};
await call('Storage.clearDataForOrigin',{origin:'http://127.0.0.1:5173',storageTypes:'indexeddb'});await call('Page.navigate',{url:'http://127.0.0.1:5173/'});await new Promise(r=>setTimeout(r,700));
const saved=await evalCode(`(async()=>{const {createEmptyProject}=await import('/src/domain/project.ts');const {commitProject}=await import('/src/persistence/indexedDb.ts');const state=createEmptyProject('m8-large-synthetic');let total=0,seed=17;const started=performance.now();
for(let month=1;month<=12;month++){const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=3200;const ctx=canvas.getContext('2d');const image=ctx.createImageData(2400,3200);const data=image.data;for(let i=0;i<data.length;i+=4){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=seed&255;data[i+1]=(seed>>>8)&255;data[i+2]=(seed>>>16)&255;data[i+3]=255;}ctx.putImageData(image,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',0.9));canvas.width=0;canvas.height=0;const aid='a'+month,iid='i'+month;state.assets[aid]={id:aid,blob,mime:'image/jpeg',fileName:'synthetic-'+month+'.jpg',byteSize:blob.size,decodedWidth:2400,decodedHeight:3200,importedAt:''};state.project.photoItems[iid]={id:iid,assetId:aid,createdAt:''};state.project.months[month].photoItemId=iid;state.project.months[month].crop={zoom:1,offsetX:0,offsetY:0};total+=blob.size;}
const builtMs=Math.round(performance.now()-started);const saveStart=performance.now();const project=await commitProject(state,null);const saveMs=Math.round(performance.now()-saveStart);return {total,assets:Object.keys(state.assets).length,revision:project.revision,builtMs,saveMs,estimate:await navigator.storage.estimate()};})()`);
console.log('saved',saved);assert.equal(saved.assets,12);assert.ok(saved.total>12_000_000);await call('Page.navigate',{url:'http://127.0.0.1:5173/'});await new Promise(r=>setTimeout(r,800));
const restored=await evalCode(`(async()=>{const {loadProject}=await import('/src/persistence/indexedDb.ts');const state=await loadProject();const assets=Object.values(state.assets);let total=assets.reduce((sum,a)=>sum+a.blob.size,0);const first=await createImageBitmap(assets[0].blob);const last=await createImageBitmap(assets[11].blob);const dimensions=[[first.width,first.height],[last.width,last.height]];first.close();last.close();return {assets:assets.length,total,ready:Object.values(state.project.months).filter(m=>m.photoItemId).length,revision:state.project.revision,dimensions,estimate:await navigator.storage.estimate()};})()`);
console.log('restored',restored);assert.equal(restored.assets,12);assert.equal(restored.total,saved.total);assert.equal(restored.ready,12);assert.equal(restored.revision,1);assert.deepEqual(restored.dimensions,[[2400,3200],[2400,3200]]);ws.close();
