// Disposable Session 05 experiment. No production-state or architecture contract.
const $ = id => document.getElementById(id);
const W=1200,H=1800, PHOTO={x:0,y:0,w:1200,h:1044}, WEEK=['S','M','T','W','T','F','S'];
const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];
const state={files:[],file:null,img:null,imgURL:null,zoom:1,dx:0,dy:0,lastBlob:null,lastPngBlob:null,lastZipBlob:null,lastBatchItems:null,lastURL:null,cancel:false,fail:false,revision:0,conflict:false};
const log=(id,x)=>$(id).textContent=typeof x==='string'?x:JSON.stringify(x,null,2);
log('environment',{userAgent:navigator.userAgent,secureContext:isSecureContext,shareAPI:typeof navigator.share,canShareAPI:typeof navigator.canShare,viewport:[innerWidth,innerHeight],devicePixelRatio});
const sleep=()=>new Promise(r=>setTimeout(r,0));
function rgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
function linear(v){v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}
function luminance(hex){const c=rgb(hex);return .2126*linear(c[0])+.7152*linear(c[1])+.0722*linear(c[2]);}
function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
function inkColor(){const bg=$('bg').value;if($('textMode').value==='custom')return $('ink').value;return contrast(bg,'#ffffff')>=contrast(bg,'#1e211f')?'#ffffff':'#1e211f';}
function contrastInfo(){const bg=$('bg').value,ink=inkColor(),ratio=contrast(bg,ink);$('contrast').textContent=`Text token ${ink} · contrast ${ratio.toFixed(2)}:1`+($('textMode').value==='custom'&&ratio<4.5?' · LOW CONTRAST (warning only)':'');return {bg,ink,ratio};}
function fillGeometry(iw,ih,fw,fh,zoom=1,dx=0,dy=0){const scale=Math.max(fw/iw,fh/ih)*zoom,w=iw*scale,h=ih*scale;return {scale,w,h,x:Math.min(0,Math.max(fw-w,(fw-w)/2+dx)),y:Math.min(0,Math.max(fh-h,(fh-h)/2+dy))};}
function clampCrop(){if(!state.img)return;const g=fillGeometry(state.img.naturalWidth,state.img.naturalHeight,PHOTO.w,PHOTO.h,state.zoom);state.dx=Math.max((PHOTO.w-g.w)/2,Math.min((g.w-PHOTO.w)/2,state.dx));state.dy=Math.max((PHOTO.h-g.h)/2,Math.min((g.h-PHOTO.h)/2,state.dy));}
function cropGeometry(){if(!state.img)return null;const e=$('crop'),fw=e.clientWidth,fh=e.clientHeight;return fillGeometry(state.img.naturalWidth,state.img.naturalHeight,fw,fh,state.zoom,state.dx*fw/PHOTO.w,state.dy*fh/PHOTO.h);}
function updateCrop(){clampCrop();const g=cropGeometry();if(!g)return;const e=$('cropImage'),fw=$('crop').clientWidth,fh=$('crop').clientHeight;e.style.width=g.w+'px';e.style.height=g.h+'px';e.style.left=g.x+'px';e.style.top=g.y+'px';log('cropLog',{source:[state.img.naturalWidth,state.img.naturalHeight],viewport:[fw,fh],outputPhotoRegion:PHOTO,zoom:state.zoom,offsetOutputPx:[state.dx,state.dy],movableOutputPx:[+(g.w*PHOTO.w/fw-PHOTO.w).toFixed(1),+(g.h*PHOTO.h/fh-PHOTO.h).toFixed(1)],covered:g.x<=0&&g.y<=0&&g.x+g.w>=fw&&g.y+g.h>=fh});}
function resetCrop(){state.zoom=1;state.dx=0;state.dy=0;$('zoom').value='1';updateCrop();drawPreview();}
async function decode(file){const result={name:file.name,type:file.type,size:file.size,lastModified:file.lastModified};const t=performance.now();try{const b=await createImageBitmap(file);result.bitmap=[b.width,b.height];result.bitmapMs=+(performance.now()-t).toFixed(1);b.close();}catch(e){result.bitmapError=String(e);}const u=URL.createObjectURL(file);try{const im=new Image();im.src=u;await im.decode();result.img=[im.naturalWidth,im.naturalHeight];result.imgMs=+(performance.now()-t).toFixed(1);return {result,img:im,url:u};}catch(e){result.imgError=String(e);URL.revokeObjectURL(u);return {result};}}
async function selectFiles(files){const list=[],readable=[];for(const f of files){const d=await decode(f);list.push(d.result);if(d.img)readable.push({file:f,decoded:d});else if(d.url)URL.revokeObjectURL(d.url);}log('pickerLog',{count:files.length,readableCount:readable.length,returnedOrder:list.map(x=>x.name),files:list,notice:'File metadata contains no guaranteed original EXIF orientation field; decoded dimensions are browser-normalized.'});$('selectedSummary').textContent=`Selected: ${files.length} photos · 当前预览月份: January · 整套导出将处理 12 个月`;if(!readable.length)return;const first=readable[0];for(const x of readable.slice(1))URL.revokeObjectURL(x.decoded.url);if(state.imgURL)URL.revokeObjectURL(state.imgURL);state.files=readable.map(x=>x.file);state.file=first.file;state.img=first.decoded.img;state.imgURL=first.decoded.url;$('cropImage').src=state.imgURL;resetCrop();}
$('photos').addEventListener('change',e=>selectFiles([...e.target.files]));$('clear').onclick=()=>{$('photos').value='';log('pickerLog','picker cleared; selected project photo remains until a new selection');};
$('reset').onclick=resetCrop;$('zoom').oninput=e=>{state.zoom=+e.target.value;updateCrop();drawPreview();};
const pointers=new Map();let start=null,dragSurface=null;
for(const surface of [$('crop'),$('preview')]){
  surface.addEventListener('pointerdown',e=>{if(!state.img)return;const rect=surface.getBoundingClientRect();if(surface.id==='preview'&&e.clientY>rect.top+rect.height*PHOTO.h/H)return;e.preventDefault();surface.setPointerCapture(e.pointerId);dragSurface=surface;pointers.set(e.pointerId,[e.clientX,e.clientY]);start={pts:new Map(pointers),dx:state.dx,dy:state.dy,zoom:state.zoom};});
  surface.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!state.img||dragSurface!==surface)return;e.preventDefault();pointers.set(e.pointerId,[e.clientX,e.clientY]);const ids=[...pointers.keys()],factor=PHOTO.w/surface.getBoundingClientRect().width;if(ids.length===1){const p=pointers.get(ids[0]),s=start.pts.get(ids[0]);state.dx=start.dx+(p[0]-s[0])*factor;state.dy=start.dy+(p[1]-s[1])*factor;}else if(ids.length>=2){const a=pointers.get(ids[0]),b=pointers.get(ids[1]),sa=start.pts.get(ids[0]),sb=start.pts.get(ids[1]);if(sa&&sb){state.zoom=Math.min(3,Math.max(1,start.zoom*Math.hypot(a[0]-b[0],a[1]-b[1])/Math.hypot(sa[0]-sb[0],sa[1]-sb[1])));$('zoom').value=state.zoom;state.dx=start.dx+(a[0]+b[0]-sa[0]-sb[0])*factor/2;state.dy=start.dy+(a[1]+b[1]-sa[1]-sb[1])*factor/2;}}updateCrop();drawPreview();});
  const end=e=>{pointers.delete(e.pointerId);if(pointers.size)start={pts:new Map(pointers),dx:state.dx,dy:state.dy,zoom:state.zoom};else dragSurface=null;};
  surface.addEventListener('pointerup',end);surface.addEventListener('pointercancel',end);
}
function calendarCells(month){const start=new Date(Date.UTC(2027,month,1)).getUTCDay(),count=new Date(Date.UTC(2027,month+1,0)).getUTCDate();return Array.from({length:42},(_,i)=>i>=start&&i<start+count?i-start+1:'');}
function fontFamily(){return {sans:'"Instrument Sans",Arial,sans-serif',serif:'"Instrument Serif",Georgia,serif',hand:'"Patrick Hand","Comic Sans MS",cursive'}[$('font').value];}
async function ensureFont(){const family=fontFamily(),target=family.split(',')[0].replaceAll('"','');let error=null,loadedFromRequest=[];try{loadedFromRequest=await document.fonts.load(`48px ${family}`);}catch(e){error=String(e);}await document.fonts.ready;const faces=[...document.fonts].filter(x=>x.family.replaceAll('"','')===target).map(x=>({family:x.family,status:x.status}));const loaded=faces.some(x=>x.status==='loaded');return {selected:$('font').value,family,target,loaded,fallback:!loaded,error,faces,requestCount:loadedFromRequest.length,documentFontsStatus:document.fonts.status,documentFontsCheck:document.fonts.check(`48px "${target}"`)};}
function draw(ctx,month=0){const {bg,ink}=contrastInfo();const s=ctx.canvas.width/W;ctx.save();ctx.scale(s,s);ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);if(state.img){const g=fillGeometry(state.img.naturalWidth,state.img.naturalHeight,PHOTO.w,PHOTO.h,state.zoom,state.dx,state.dy);ctx.save();ctx.beginPath();ctx.rect(PHOTO.x,PHOTO.y,PHOTO.w,PHOTO.h);ctx.clip();ctx.drawImage(state.img,PHOTO.x+g.x,PHOTO.y+g.y,g.w,g.h);ctx.restore();}ctx.fillStyle=ink;ctx.textBaseline='alphabetic';ctx.font=`92px ${fontFamily()}`;ctx.textAlign='left';ctx.fillText(monthNames[month],95,1340);ctx.font=`39px ${fontFamily()}`;ctx.textAlign='right';ctx.fillText('2027',1104,1338);ctx.textAlign='center';ctx.font=`32px ${fontFamily()}`;const xs=Array.from({length:7},(_,i)=>130+i*156.5);WEEK.forEach((v,i)=>ctx.fillText(v,xs[i],1436));ctx.font=`34px ${fontFamily()}`;calendarCells(month).forEach((v,i)=>{if(v)ctx.fillText(String(v),xs[i%7],1500+Math.floor(i/7)*48);});ctx.restore();}
async function drawPreview(){const selected=$('font').value,info=await ensureFont();if(selected!==$('font').value)return;const sample=$('fontSample');sample.style.fontFamily=info.family;const ctx=$('preview').getContext('2d');draw(ctx,0);ctx.font=`92px ${info.family}`;const titleWidth=ctx.measureText('January').width,data=ctx.getImageData(0,400,400,200).data;let hash=2166136261;for(let i=0;i<data.length;i+=8)hash=Math.imul(hash^data[i],16777619)>>>0;log('fontLog',{...info,cssFontFamily:getComputedStyle(sample).fontFamily,canvasFont:ctx.font,canvasJanuaryWidth:+titleWidth.toFixed(2),previewTextHash:hash,previewMonth:'January'});}
function toBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('toBlob returned null')),'image/png'));}
async function renderCanvas(month){await ensureFont();const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;draw(canvas.getContext('2d'),month);const blob=await toBlob(canvas);canvas.width=canvas.height=0;return blob;}
function bytesToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
async function renderSvg(month){await ensureFont();const photo=state.file?await bytesToDataURL(state.file):null;const g=state.img?fillGeometry(state.img.naturalWidth,state.img.naturalHeight,PHOTO.w,PHOTO.h,state.zoom,state.dx,state.dy):null;const {bg,ink}=contrastInfo();const cells=calendarCells(month).map((v,i)=>v?`<text x="${130+i%7*156.5}" y="${1500+Math.floor(i/7)*48}" text-anchor="middle" font-size="34">${v}</text>`:'').join('');const week=WEEK.map((v,i)=>`<text x="${130+i*156.5}" y="1436" text-anchor="middle" font-size="32">${v}</text>`).join('');const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1800"><defs><clipPath id="p"><rect x="${PHOTO.x}" y="${PHOTO.y}" width="${PHOTO.w}" height="${PHOTO.h}"/></clipPath></defs><rect width="1200" height="1800" fill="${bg}"/>${photo?`<image href="${photo}" x="${PHOTO.x+g.x}" y="${PHOTO.y+g.y}" width="${g.w}" height="${g.h}" clip-path="url(#p)" preserveAspectRatio="none"/>`:''}<g fill="${ink}" font-family="${fontFamily().split(',')[0].replaceAll('"','')}"><text x="95" y="1340" font-size="92">${monthNames[month]}</text><text x="1104" y="1338" text-anchor="end" font-size="39">2027</text>${week}${cells}</g></svg>`;const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const image=new Image();image.src=url;await image.decode();const c=document.createElement('canvas');c.width=W;c.height=H;c.getContext('2d').drawImage(image,0,0);const b=await toBlob(c);c.width=c.height=0;return b;}finally{URL.revokeObjectURL(url);}}
function rememberBlob(blob){if(state.lastURL)URL.revokeObjectURL(state.lastURL);state.lastBlob=blob;state.lastURL=URL.createObjectURL(blob);}
const preparedURLs={png:null,zip:null};
function prepareLink(kind,blob,name){const id=kind==='png'?'preparedPngLink':'preparedZipLink',a=$(id);if(preparedURLs[kind])URL.revokeObjectURL(preparedURLs[kind]);const url=URL.createObjectURL(blob);preparedURLs[kind]=url;a.href=url;a.download=name;a.hidden=false;log('handoffLog',{stage:'Blob ready; no device save verified',kind,name,bytes:blob.size,mime:blob.type,urlScheme:'blob:',time:new Date().toISOString(),secureContext:isSecureContext});return url;}
function requestDownload(kind,blob,name,source){const url=preparedURLs[kind]||prepareLink(kind,blob,name),active=navigator.userActivation?.isActive??null,a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();log('handoffLog',{stage:'download click dispatched; device save unverified',kind,source,name,bytes:blob.size,mime:blob.type,userActivationAtClick:active,time:new Date().toISOString(),visibility:document.visibilityState});}
for(const [kind,id] of [['png','preparedPngLink'],['zip','preparedZipLink']])$(id).addEventListener('click',()=>{const blob=kind==='png'?state.lastPngBlob:state.lastZipBlob;log('handoffLog',{stage:'direct visible link clicked; device save unverified',kind,name:$(id).download,bytes:blob?.size??null,userActivationAtClick:navigator.userActivation?.isActive??null,time:new Date().toISOString()});});
async function exportOne(path='canvas'){const t=performance.now();const blob=path==='svg'?await renderSvg(0):await renderCanvas(0);rememberBlob(blob);state.lastPngBlob=blob;prepareLink('png',blob,path==='svg'?'01-January-2027-svg-path.png':'01-January-2027.png');const info={path,bytes:blob.size,mime:blob.type,dimensions:[1200,1800],ms:+(performance.now()-t).toFixed(1),font:await ensureFont(),contrast:contrastInfo()};log('exportLog',info);return blob;}
$('png').onclick=async()=>{try{const blob=await exportOne();requestDownload('png',blob,'01-January-2027.png','after async generation');}catch(e){log('exportLog',String(e));}};
$('svgPng').onclick=async()=>{try{const blob=await exportOne('svg');requestDownload('png',blob,'01-January-2027-svg-path.png','after async SVG generation');}catch(e){log('exportLog',String(e));}};
$('openPng').onclick=()=>{try{if(!state.lastPngBlob||!preparedURLs.png)throw Error('Generate PNG first');const opened=window.open(preparedURLs.png,'_blank');log('handoffLog',{stage:'open prepared PNG requested; actual viewer unverified',name:$('preparedPngLink').download,bytes:state.lastPngBlob.size,windowOpened:!!opened,userActivationAtClick:navigator.userActivation?.isActive??null,time:new Date().toISOString()});}catch(e){log('handoffLog',{stage:'open failed',error:String(e)});}};
$('sharePng').onclick=async()=>{try{const b=state.lastPngBlob;if(!b)throw Error('Generate PNG first, then tap Share as a separate gesture');const file=new File([b],'01-January-2027.png',{type:'image/png'});if(!navigator.canShare?.({files:[file]}))throw Error('navigator.canShare(files) unavailable/false');await navigator.share({files:[file],title:'January 2027'});log('exportLog','navigator.share completed');}catch(e){log('exportLog',`${e.name}: ${e.message}`);}};
['bg','ink','textMode','font'].forEach(id=>{for(const event of ['input','change'])$(id).addEventListener(event,()=>drawPreview());});
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function zipStore(items){const te=new TextEncoder(),chunks=[],central=[];let offset=0;for(const {name,bytes} of items){const n=te.encode(name),crc=crc32(bytes),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);h.set(n,30);chunks.push(h,bytes);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,crc,true);d.setUint32(20,bytes.length,true);d.setUint32(24,bytes.length,true);d.setUint16(28,n.length,true);d.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+bytes.length;}const cdSize=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),dv=new DataView(end.buffer);dv.setUint32(0,0x06054b50,true);dv.setUint16(8,items.length,true);dv.setUint16(10,items.length,true);dv.setUint32(12,cdSize,true);dv.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
async function batch(){state.cancel=false;state.lastBatchItems=null;const t=performance.now(),items=[],samples=[];try{for(let m=0;m<12;m++){if(state.cancel)throw Error('Cancelled before month '+(m+1));if(state.fail&&m===3){state.fail=false;throw Error('Injected month 4 failure');}const b=await renderCanvas(m);items.push({name:`${String(m+1).padStart(2,'0')}-${monthNames[m]}-2027.png`,bytes:new Uint8Array(await b.arrayBuffer())});samples.push({month:m+1,ms:+(performance.now()-t).toFixed(1),bytes:b.size,memory:performance.memory?.usedJSHeapSize??null});log('zipLog',{stage:'generating separate PNGs',progress:`${m+1}/12`,samples});await sleep();}log('zipLog',{stage:'packaging ZIP',generatedPngs:items.length});const zip=zipStore(items);state.lastBatchItems=items;state.lastZipBlob=zip;rememberBlob(zip);prepareLink('zip',zip,'2027-calendar.zip');requestDownload('zip',zip,'2027-calendar.zip','after async batch generation');log('zipLog',{status:'generated; download requested, device save unverified',generatedPngs:items.length,delivery:'ZIP',ms:+(performance.now()-t).toFixed(1),zipBytes:zip.size,samples,storage:await navigator.storage?.estimate?.()});return zip;}catch(e){log('zipLog',{status:'failed',error:String(e),generated:items.length,samples});throw e;}}
$('zip').onclick=()=>batch().catch(()=>{});$('cancelZip').onclick=()=>{state.cancel=true;};$('failZip').onclick=()=>{state.fail=true;};
$('shareSet').onclick=async()=>{try{if(!isSecureContext)throw Error('REAL HTTPS DEVICE TEST REQUIRED: LAN HTTP cannot settle Web Share');if(!state.lastBatchItems?.length)throw Error('Generate the 12 PNGs first, then tap Share as a separate gesture');const files=state.lastBatchItems.map(x=>new File([x.bytes],x.name,{type:'image/png'}));const canShare=!!navigator.canShare?.({files});log('zipLog',{stage:'multi-file Web Share probe',count:files.length,bytes:files.reduce((n,f)=>n+f.size,0),shareAPI:typeof navigator.share,canShare});if(!canShare)throw Error('navigator.canShare({files}) returned false');await navigator.share({files,title:'2027 calendar'});log('zipLog',{status:'share call resolved',count:files.length,note:'Confirm actual Files/Photos destination manually'});}catch(e){log('zipLog',{status:'multi-file share not validated',error:`${e.name}: ${e.message}`});}};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('calendar-spike-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function storeProject(){const db=await openDB();try{const tx=db.transaction('data','readwrite'),s=tx.objectStore('data'),current=await req(s.get('project'));if(current&&current.revision!==state.revision){state.conflict=true;tx.abort();throw Error(`stale revision ${state.revision}; saved ${current.revision}`);}const next={revision:state.revision+1,files:state.files,monthAssignments:Array.from({length:12},(_,i)=>i<state.files.length?i:null),crop:{zoom:state.zoom,dx:state.dx,dy:state.dy},colors:{bg:$('bg').value,mode:$('textMode').value,custom:$('ink').value},typography:$('font').value,stamp:Date.now()};s.put(next,'project');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||Error('transaction aborted'));tx.onerror=()=>reject(tx.error);});state.revision=next.revision;channel?.postMessage({revision:next.revision});return {revision:next.revision,files:next.files.length,bytes:next.files.reduce((a,b)=>a+b.size,0),quota:await navigator.storage?.estimate?.()};}finally{db.close();}}
async function restoreProject(){const db=await openDB();try{const tx=db.transaction('data','readonly'),p=await req(tx.objectStore('data').get('project'));if(!p)return null;state.revision=p.revision;state.conflict=false;return {revision:p.revision,files:p.files.map(f=>({name:f.name,size:f.size,type:f.type})),assignments:p.monthAssignments,crop:p.crop,colors:p.colors,typography:p.typography,quota:await navigator.storage?.estimate?.()};}finally{db.close();}}
const channel=typeof BroadcastChannel==='undefined'?null:new BroadcastChannel('calendar-spike');channel?.addEventListener('message',e=>{if(e.data.revision>state.revision){state.conflict=true;log('storageLog',{status:'NEWER TAB — writes blocked',current:state.revision,newer:e.data.revision});}});
$('store').onclick=async()=>{try{if(state.conflict)throw Error('newer tab conflict; refresh/restore required');log('storageLog',await storeProject());}catch(e){log('storageLog',{status:'save failed; last valid project retained',error:String(e)});}};
$('restore').onclick=async()=>{try{log('storageLog',await restoreProject());}catch(e){log('storageLog',String(e));}};
$('writeRevision').onclick=async()=>{try{log('storageLog',await storeProject());}catch(e){log('storageLog',String(e));}};
$('testQuota').onclick=async()=>log('storageLog',await navigator.storage?.estimate?.());
window.spike={state,decode,selectFiles,fillGeometry,calendarCells,contrast,inkColor,ensureFont,renderCanvas,renderSvg,exportOne,batch,storeProject,restoreProject,zipStore,resetCrop};
drawPreview();
