// Disposable real-browser measurement harness. Uses installed Chrome/Edge, not emulation.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/soulkid/AppData/Local/OpenAI/Codex/runtimes/cua_node/df473e5367fa2b42/bin/node_modules/playwright');
const root=__dirname,out=path.join(root,'results');fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.ttf':'font/ttf','.txt':'text/plain'};
const server=http.createServer((req,res)=>{const uri=decodeURIComponent(new URL(req.url,'http://local').pathname),p=path.resolve(root,'.'+(uri==='/'?'/index.html':uri));if(!p.startsWith(root)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{if(e){res.writeHead(404).end(String(e));return;}res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream'}).end(b);});});
const browserPaths={Chrome:'C:/Program Files/Google/Chrome/Application/chrome.exe',Edge:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'};
const srcDir='C:/Windows/Web/Wallpaper';
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(path.join(dir,x.name)):x.name.toLowerCase().match(/\.jpe?g$/)?[path.join(dir,x.name)]:[]);}
const orientSource=fs.readFileSync('C:/Windows/Web/Wallpaper/Lenovo/LenovoWallPaper.jpg');const tiff=Buffer.from([0x49,0x49,0x2a,0,8,0,0,0,1,0,0x12,1,3,0,1,0,0,0,6,0,0,0,0,0,0,0]);const exif=Buffer.concat([Buffer.from('Exif\0\0'),tiff]),header=Buffer.alloc(4);header.writeUInt16BE(0xffe1,0);header.writeUInt16BE(exif.length+2,2);fs.writeFileSync(path.join(out,'orientation6.jpg'),Buffer.concat([orientSource.subarray(0,2),header,exif,orientSource.subarray(2)]));
function pngInfo(buffer){return {signature:buffer.subarray(0,8).toString('hex'),width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20),bytes:buffer.length};}
async function run(name,exe){const browser=await chromium.launch({executablePath:exe,headless:true});const ctx=await browser.newContext({acceptDownloads:true});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:4175/');
  const result={environment:{browser:name,version:browser.version(),platform:process.platform,headless:true,realBrowser:true},sourcePhotos:[],tests:{},errors};
  const photoFiles=files(srcDir).filter(f=>fs.statSync(f).size>100000).slice(0,12);result.sourcePhotos=photoFiles.map(f=>({name:path.basename(f),bytes:fs.statSync(f).size}));
  await page.locator('#photos').setInputFiles(photoFiles);await page.waitForFunction(()=>window.spike.state.files.length===12);result.tests.fileList=await page.evaluate(()=>JSON.parse(document.querySelector('#pickerLog').textContent));
  result.tests.heic=await page.evaluate(async()=>{const b=await (await fetch('/samples/libheif-example.heic')).blob();return (await spike.decode(new File([b],'libheif-example.heic',{type:'image/heic'}))).result;});
  result.tests.orientation=await page.evaluate(async()=>{const b=await (await fetch('/results/orientation6.jpg')).blob();return (await spike.decode(new File([b],'orientation6.jpg',{type:'image/jpeg'}))).result;});
  result.tests.formats=await page.evaluate(async()=>{const src=spike.state.files[0],bm=await createImageBitmap(src),c=document.createElement('canvas');c.width=bm.width;c.height=bm.height;c.getContext('2d').drawImage(bm,0,0);bm.close();const out={};for(const [type,ext] of [['image/png','png'],['image/webp','webp'],['image/jpeg','jpg']]){const b=await new Promise(r=>c.toBlob(r,type,.9));out[ext]=(await spike.decode(new File([b],'sample.'+ext,{type}))).result;}c.width=c.height=0;return out;});
  result.tests.cropMath=await page.evaluate(()=>{const cases=[[400,600],[600,400],[500,500],[4000,300],[300,4000]];return cases.map(([w,h])=>{const g=spike.fillGeometry(w,h,300,450,1.75,999,-999);return {source:[w,h],covered:g.x<=0&&g.y<=0&&g.x+g.w>=300&&g.y+g.h>=450,geometry:g};});});
  await page.locator('#crop').scrollIntoViewIfNeeded();const box=await page.locator('#crop').boundingBox();await page.mouse.move(box.x+150,box.y+225);await page.mouse.down();await page.mouse.move(box.x+205,box.y+190,{steps:4});await page.mouse.up();result.tests.pointerDrag=await page.evaluate(()=>({dx:spike.state.dx,dy:spike.state.dy,covered:JSON.parse(document.querySelector('#cropLog').textContent).covered}));
  result.tests.calendar=await page.evaluate(()=>({cells:spike.calendarCells(0),rowCount:spike.calendarCells(0).length}));
  result.tests.fonts={};for(const font of ['sans','serif','hand']){await page.selectOption('#font',font);result.tests.fonts[font]=await page.evaluate(()=>spike.ensureFont());}
  await page.selectOption('#font','serif');await page.locator('#bg').evaluate(e=>{e.value='#232a3b';e.dispatchEvent(new Event('input',{bubbles:true}));});
  result.tests.contrast=await page.evaluate(()=>['#ffffff','#777777','#232a3b','#e00055','#00a0ff'].map(bg=>{document.querySelector('#bg').value=bg;return {bg,ink:spike.inkColor(),ratio:spike.contrast(bg,spike.inkColor())};}));
  await page.evaluate(()=>{document.querySelector('#bg').value='#232a3b';document.querySelector('#textMode').value='custom';document.querySelector('#ink').value='#232a3b';document.querySelector('#ink').dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForFunction(()=>document.querySelector('#contrast').textContent.includes('LOW CONTRAST'));result.tests.customContrast=await page.evaluate(()=>({ink:spike.inkColor(),warning:document.querySelector('#contrast').textContent}));await page.selectOption('#textMode','auto');
  await page.locator('#bg').evaluate(e=>{e.value='#232a3b';e.dispatchEvent(new Event('input',{bubbles:true}));});
  const canvasBlob=await page.evaluate(()=>spike.renderCanvas(0).then(b=>b.arrayBuffer()).then(a=>Array.from(new Uint8Array(a))));const canvasBuffer=Buffer.from(canvasBlob);fs.writeFileSync(path.join(out,`${name}-canvas.png`),canvasBuffer);result.tests.canvasPng=pngInfo(canvasBuffer);
  const svgBlob=await page.evaluate(()=>spike.renderSvg(0).then(b=>b.arrayBuffer()).then(a=>Array.from(new Uint8Array(a))));const svgBuffer=Buffer.from(svgBlob);fs.writeFileSync(path.join(out,`${name}-svg.png`),svgBuffer);result.tests.svgPng=pngInfo(svgBuffer);
  result.tests.pngPixels=await page.evaluate(async()=>{const b1=await spike.renderCanvas(0),b2=await spike.renderSvg(0);const read=async b=>{const bm=await createImageBitmap(b),c=document.createElement('canvas');c.width=1200;c.height=1800;c.getContext('2d').drawImage(bm,0,0);bm.close();const x=c.getContext('2d');return {photo:[...x.getImageData(600,500,1,1).data],background:[...x.getImageData(20,1500,1,1).data],heading:[...x.getImageData(100,1300,1,1).data]};};return {canvas:await read(b1),svg:await read(b2)};});
  result.tests.repeatedExport=await page.evaluate(async()=>{const rows=[];for(let i=0;i<3;i++){const t=performance.now(),b=await spike.renderCanvas(0);rows.push({run:i+1,bytes:b.size,ms:+(performance.now()-t).toFixed(1),usedJSHeapSize:performance.memory?.usedJSHeapSize??null});}return rows;});
  result.tests.previewExport=await page.evaluate(async()=>{await new Promise(r=>setTimeout(r,50));const p=document.querySelector('#preview'),b=await spike.renderCanvas(0),im=await createImageBitmap(b),c=document.createElement('canvas');c.width=400;c.height=600;c.getContext('2d').drawImage(im,0,0,400,600);im.close();const a=p.getContext('2d').getImageData(0,0,400,600).data,d=c.getContext('2d').getImageData(0,0,400,600).data;let sum=0,n=0;for(let i=0;i<a.length;i+=80){sum+=Math.abs(a[i]-d[i])+Math.abs(a[i+1]-d[i+1])+Math.abs(a[i+2]-d[i+2]);n+=3;}return {sampledChannels:n,meanAbsoluteChannelDifference:+(sum/n).toFixed(2)};});
  await page.click('#zip');await page.click('#cancelZip');await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#zipLog').textContent).status==='failed'}catch{return false}},{timeout:30000});result.tests.zipCancel=JSON.parse(await page.locator('#zipLog').textContent());
  await page.click('#failZip');await page.click('#zip');await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#zipLog').textContent).error?.includes('Injected month 4 failure')}catch{return false}});result.tests.zipInjectedFailure=JSON.parse(await page.locator('#zipLog').textContent());
  const zipDownloadPromise=page.waitForEvent('download',{timeout:120000});await page.click('#zip');const zipDownload=await zipDownloadPromise;const zipPath=path.join(out,`${name}-12-months.zip`);await zipDownload.saveAs(zipPath);const zipBuffer=fs.readFileSync(zipPath);result.tests.zip={bytes:zipBuffer.length,localEntries:[...zipBuffer.toString('latin1').matchAll(/PK\x03\x04/g)].length,log:JSON.parse(await page.locator('#zipLog').textContent())};
  result.tests.storage=await page.evaluate(()=>spike.storeProject());await page.reload();result.tests.storageReload=await page.evaluate(()=>spike.restoreProject());
  const second=await ctx.newPage();await second.goto('http://127.0.0.1:4175/');await second.evaluate(()=>spike.restoreProject());await second.evaluate(()=>spike.storeProject());result.tests.multiTab=await page.evaluate(async()=>{await new Promise(r=>setTimeout(r,100));try{await spike.storeProject();return {unexpected:'write succeeded',conflict:spike.state.conflict};}catch(e){return {error:String(e),conflict:spike.state.conflict};}});
  result.tests.resources=await page.evaluate(()=>performance.getEntriesByType('resource').filter(x=>x.name.endsWith('.ttf')).map(x=>({name:x.name.split('/').at(-1),transferSize:x.transferSize,decodedBodySize:x.decodedBodySize})));
  await ctx.close();await browser.close();return result;}
server.listen(4175,'127.0.0.1',async()=>{const report={runAt:new Date().toISOString(),results:[]};for(const [name,exe] of Object.entries(browserPaths)){try{report.results.push(await run(name,exe));}catch(e){report.results.push({browser:name,fatal:String(e),stack:e.stack});}}fs.writeFileSync(path.join(out,'desktop-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.results.map(r=>({browser:r.environment?.browser||r.browser,version:r.environment?.version,fatal:r.fatal,errors:r.errors,zip:r.tests?.zip?.bytes,storage:r.tests?.storage?.bytes,conflict:r.tests?.multiTab})),null,2));server.close();});
